### PR TITLE
Dev <- Pyodide

### PR DESCRIPTION
**Pull request by yongrenjie**
Rebase of @stuartlynn's Pyiodide work onto dev branch.

### CODE REVIEW

**Comment by yongrenjie** [comment]
`npm run build` fails. This is to do with the lack of node polyfills in vite, but even after installing https://www.npmjs.com/package/vite-plugin-node-polyfills it doesn't work. Suspect it's related to https://github.com/davidmyersdev/vite-plugin-node-polyfills/issues/48, but still investigating.

**Comment by stuartlynn** [comment]
> `npm run build` fails. This is to do with the lack of node polyfills in vite, but even after installing https://www.npmjs.com/package/vite-plugin-node-polyfills it doesn't work. Suspect it's related to [davidmyersdev/vite-plugin-node-polyfills#48](https://github.com/davidmyersdev/vite-plugin-node-polyfills/issues/48), but still investigating.

Try adding this back in https://github.com/Urban-Analytics-Technology-Platform/demoland-web/blob/287608b6c570c75e6b56a043f0f3dc46e8233672/web/vite.config.ts#L12-L17 I think that stubs out enough to get the build working

**Comment by yongrenjie** [comment]
@stuartlynn Hmm ... missed that. But it's still not happy :(

```
$ npm run build

> demoland-web@2.0.0-alpha build
> vite build

vite v4.3.5 building for production...
transforming (97) node_modules/overlayscrollbars/overlayscrollbars.mjs[plugin:vite:resolve] Module "node:http" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-fetch/src/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:https" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-fetch/src/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:zlib" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-fetch/src/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:stream" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-fetch/src/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:buffer" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-fetch/src/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
transforming (104) node_modules/@kurkle/color/dist/color.esm.js[plugin:vite:resolve] Module "node:stream" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-fetch/src/body.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:util" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-fetch/src/body.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:buffer" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-fetch/src/body.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:util" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-fetch/src/headers.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:http" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-fetch/src/headers.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:net" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-fetch/src/utils/referrer.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:url" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-fetch/src/request.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:util" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-fetch/src/request.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:fs" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/fetch-blob/from.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:path" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/fetch-blob/from.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "worker_threads" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/node-domexception/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:process" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/fetch-blob/streams.cjs". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:stream/web" has been externalized for browser compatibility, imported by "/Users/jyong/demoland/web/web/node_modules/fetch-blob/streams.cjs". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
✓ 112 modules transformed.
✓ built in 2.61s
[vite:worker] "promisify" is not exported by "__vite-browser-external", imported by "node_modules/node-fetch/src/body.js".
file: /Users/jyong/demoland/web/web/src/lib/python/pyoide_worker.ts?worker:9:26
 7:
 8: import Stream, {PassThrough} from 'node:stream';
 9: import {types, deprecate, promisify} from 'node:util';
                              ^
10: import {Buffer} from 'node:buffer';
error during build:
RollupError: "promisify" is not exported by "__vite-browser-external", imported by "node_modules/node-fetch/src/body.js".
    at error (file:///Users/jyong/demoland/web/web/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
    at Module.error (file:///Users/jyong/demoland/web/web/node_modules/rollup/dist/es/shared/node-entry.js:13452:16)
    at Module.traceVariable (file:///Users/jyong/demoland/web/web/node_modules/rollup/dist/es/shared/node-entry.js:13863:29)
    at ModuleScope.findVariable (file:///Users/jyong/demoland/web/web/node_modules/rollup/dist/es/shared/node-entry.js:12418:39)
    at Identifier.bind (file:///Users/jyong/demoland/web/web/node_modules/rollup/dist/es/shared/node-entry.js:8116:40)
    at CallExpression.bind (file:///Users/jyong/demoland/web/web/node_modules/rollup/dist/es/shared/node-entry.js:5739:23)
    at CallExpression.bind (file:///Users/jyong/demoland/web/web/node_modules/rollup/dist/es/shared/node-entry.js:9669:15)
    at VariableDeclarator.bind (file:///Users/jyong/demoland/web/web/node_modules/rollup/dist/es/shared/node-entry.js:5739:23)
    at VariableDeclaration.bind (file:///Users/jyong/demoland/web/web/node_modules/rollup/dist/es/shared/node-entry.js:5735:28)
    at Program.bind (file:///Users/jyong/demoland/web/web/node_modules/rollup/dist/es/shared/node-entry.js:5735:28)
```

**Comment by yongrenjie** [comment]
Hmmmm I didn't realise that merging in git would automatically close this PR... haha. I'll open a new issue to track the build failure

**Pull request merged**
